### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by aharui** [emilkm/amfjs#17]
In this commit https://github.com/emilkm/amfjs/commit/e491ac29370f7994f28598393781164d823e95fc#diff-dfe09142006993477baa8e4018d02500

the header is changed to no longer mention that this code may have been derived from Surrey's r-amf.  Can you explain why?  Surrey's version appears to be LGPL so it isn't clear you can relicense this code to be under Apache License without their permission.

**Comment by emilkm** [comment]
Hi Alex,

Surrey's r-amf was the starting point of my development. Surrey's work was written for AMF 99 (a modified AMF spec). After some years of development and making the library work against the AMF 3 spec, the code has diverged enough, so I decided to change the header. I will be updating the documentation when I get some time.

Back in 2013 I wrote to Surrey and asked him if it would be ok to use his library as a starting point for my AMF 3 implementation, and change the license to Apache License, Version 2.0 He replied that he was happy for me to do so, with or without mention.

![2017-09-25_08h30_35](https://user-images.githubusercontent.com/4327531/30786301-38b8f9be-a1d0-11e7-9488-e20838c082b7.png)

I wanted to change the license since Flex itself, as well as other libraries I was working with, were all either Apache License or changing to Apache License.

I want to use this opportunity to thank you for your excellent work on Flex. Shame we have to replace it because of Flash dying.

Regards
Emil

**Comment by upayavira** [comment]
@emilkm It does look like Surrey was saying "do what you like" which kinda implies that he's okay with a relicensing. But, for Apache, it would be good if it were more explicit. Would you be willing to contact Surrey once more, and ask him a simple "yes/no" question about relicensing this code to the Apache License V2? 

For Apache, it would be great if that permission were traceable somehow from the Apache codebase, e.g. a link to a comment here, and a mention of his name.

Thanks!

**Comment by emilkm** [comment]
Hi, I don't mind at all. Will try to contact him now. Hopefully he is still to be found at the same address.

**Comment by upayavira** [comment]
Thanks @emilkm.

**Comment by emilkm** [comment]
No problem. I sent an email to the only address I have, which was (is?) Surrey's work address at Reignite. The email did not bounce immediately. 

Reignite has merged with Dashdigital, and one other company. (They could have changed their email addresses, etc) If I do not get a response within a day or two, I will try the Dashdigital contact email.

If all else fails, and you guys really need and AMF JavaScript library, I can rewrite this one from scratch. After writing one in PHP, and C (PHP extension), and stepping through the BlazeDS AMF code so many times, I am sure it won't take me as long as it did the first time :)

**Comment by emilkm** [comment]
I could not get hold of Surrey, but the Head of Development at dashdigital.com.au Sean Morrison was kind to respond promptly.

He says it is OK. 

![2017-10-03_15h44_46](https://user-images.githubusercontent.com/4327531/31108108-8a6dc3fa-a853-11e7-8d29-fc0a5e74c221.png)

Please let me know if that covers the licensing concerns for you.

**Comment by surreyhughes** [comment]
Hi guys. So good to see some good has come of my original efforts. I have moved on from reignite/ dash but Sean is right to say all is good. Go for gold. Which means i have no problems with changing licence or headers and so on.

**Comment by emilkm** [comment]
Hi Surrey,

Thank you very much for taking the time to respond. Much appreciated.
